In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('//Users//devrajjajoo//Downloads//Default_Fin.csv')

In [3]:
df.head()
df.dtypes

Index              int64
Employed           int64
Bank Balance     float64
Annual Salary    float64
Defaulted?         int64
dtype: object

In [4]:
df['Defaulted?'].value_counts()

0    9667
1     333
Name: Defaulted?, dtype: int64

In [5]:
df.corr()

Index  Employed  Bank Balance  Annual Salary  Defaulted?
Index          1.000000 -0.002597      0.010342      -0.001427   -0.005135
Employed      -0.002597  1.000000     -0.203578       0.753985   -0.035420
Bank Balance   0.010342 -0.203578      1.000000      -0.152243    0.350119
Annual Salary -0.001427  0.753985     -0.152243       1.000000   -0.019871
Defaulted?    -0.005135 -0.035420      0.350119      -0.019871    1.000000

In [6]:
data = df[['Annual Salary','Employed']].copy()

In [7]:
data.head()

Annual Salary  Employed
0      532339.56         1
1      145273.56         0
2      381205.68         1
3      428453.88         1
4      461562.00         1

In [8]:
result = df[['Defaulted?']].copy()

In [9]:
result.head()

Defaulted?
0           0
1           0
2           0
3           0
4           0

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
X = data[['Annual Salary','Employed']].copy()
X.head()

Annual Salary  Employed
0      532339.56         1
1      145273.56         0
2      381205.68         1
3      428453.88         1
4      461562.00         1

In [12]:
y = df[['Defaulted?']].copy()
y.head()

Defaulted?
0           0
1           0
2           0
3           0
4           0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

In [14]:
scaler = StandardScaler()

In [15]:
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
log_model = LogisticRegression()

In [18]:
log_model.fit(scaled_X_train,y_train)

/Users/devrajjajoo/Library/Python/3.10/lib/python/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [19]:
log_model.coef_

array([[ 0.04677389, -0.22029442]])

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [21]:
y_pred = log_model.predict(scaled_X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
accuracy_score(y_test, y_pred)

0.967

In [23]:
confusion_matrix(y_test, y_pred)

array([[967,   0],
       [ 33,   0]])

In [24]:
test = [[100000000,1]]

In [25]:
log_model.predict(test)

array([1])

In [26]:
from joblib import dump,load

In [27]:
dump(log_model,'loan_prediction_default.joblib')

['loan_prediction_default.joblib']

In [28]:
model_log = LogisticRegression()

In [29]:
model_log.fit(X_train, y_train)

/Users/devrajjajoo/Library/Python/3.10/lib/python/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [30]:
model_log.coef_

array([[-9.15157926e-06,  3.99836962e-12]])

In [31]:
y_non_scaled_pred = model_log.predict(X_test)
y_non_scaled_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
accuracy_score(y_test, y_non_scaled_pred)

0.967

In [33]:
confusion_matrix(y_test, y_non_scaled_pred)


array([[967,   0],
       [ 33,   0]])

In [34]:
model_log.predict(test)


/Users/devrajjajoo/Library/Python/3.10/lib/python/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [35]:
log_model.predict([[100000000000,1]])

array([1])

In [36]:
loaded_model = load('loan_prediction_default.joblib')

In [37]:
loaded_model.predict([[1000000000,1]])

array([1])